num = int (input("Digite um número: "))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*2))
print ("{}x{}".format(num, num*3))
print ("{}x{}".format(num, num*4))
print ("{}x{}".format(num, num*5))
print ("{}x{}".format(num, num*6))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*1))