num = int (input("Digite um número: "))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*1))
print ("{}x{}".format(num, num*1))